site_name: 流程图工具文档
site_url: ""
use_directory_urls: false

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - offline
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 'index.md'
  - 'project.md'
  - 'graph_editor.md'
  - 'debug.md'
  - 'menu_toolbar.md'
  - 'type.md'
